### ISSUE TITLE
 Version Quilt 1.4.0-beta.2 doesn't work on Quilt 0.17.0-beta.2

### ISSUE THREAD

**Issue by Trnrr** [Ellemes/container-library#19]
Downloaded from Modrinth and when I launch it gives me an error saying I need version Quilt 0.16.0-beta.12. I understand it was built to depend on 0.16.0. Just wanted to say that it works on 0.17.0.

ellemes-container-library-1.4.0-beta.2+1.18.2-quilt
qsl-1.1.0-beta.14_qfapi-1.0.0-beta.17_fapi-0.54.0_mc-1.18.2

Changing the value in quilt.mod.json to 0.17.0-beta.2 lets the client load and everything seems to be functional for the most part. The only issue I've noticed is the opening/closing animation gets stuck or doesn't play sometimes. When it gets stuck it just vibrates back and forth. It was most reproducible on the single chest. I only noticed it once on the long double chest

![image](https://user-images.githubusercontent.com/20446954/172032098-69476cf9-302e-4cbe-82cc-a0c021528672.png)

**Comment by Ellemes** [comment]
Sorry about the version contraint issue, will push a fix for that soon. Not really sure what would cause the lids to do this but I'll see if I can look into it soon-ish.

**Comment by Ellemes** [comment]
Will open an issue on Expanded Storage's repo about the lid issue but I'm not sure of the cause since it doesn't happen for me.
