### ISSUE TITLE
Critical Injection Failure with latest version of Forge

### ISSUE THREAD

**Issue by Gamemassa** [Ellemes/container-library#23]
Hi,

I just tried to load up Minecraft earlier and I got a crash log. I posted the crash log on the Forge forums and one of the friendly users over there isolated the following section for me:

Exception message: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on ncl_noPacketOnFail could not find any targets matching 'useItemOn(Lnet/minecraft/client/player/LocalPlayer;Lnet/minecraft/world/InteractionHand;Lnet/minecraft/world/phys/BlockHitResult;)Lnet/minecraft/world/InteractionResult;' in net.minecraft.client.multiplayer.MultiPlayerGameMode. No refMap loaded. [PREINJECT Applicator Phase -> ellemes-container-library-forge.mixins.json:ClientPlayerInteractionManagerMixin -> Prepare Injections ->  -> handler$zza000$ncl_noPacketOnFail(Lnet/minecraft/client/player/LocalPlayer;Lnet/minecraft/world/InteractionHand;Lnet/minecraft/world/phys/BlockHitResult;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]

He said it appears to be an issue with Ellemes Container Library and that I should repost it here, so I have (and I've attached the crash report as well).

[crash-2022-07-09_14.09.21-fml.txt](https://github.com/Ellemes/container-library/files/9077765/crash-2022-07-09_14.09.21-fml.txt)

**Comment by Ellemes** [comment]
Thanks for reporting, thought the changes I did in 2.0.2 would have fixed this but apparently not, will look into it right now.

**Comment by Gamemassa** [comment]
Thank you so much for the quick reply. I'm not sure if the fact that Forge had been updated 2 hours ago makes a difference with the changes you're referring to, but if it helps, the latest version (which I'm using) is 41.0.85

**Comment by Ellemes** [comment]
Nope, it's another typo on my end from where I renamed a file but didn't update my build code to refer to the updated file...

Got a new build releasing now, will try and implement a better fix so it isn't as easily broken.

**Comment by Ellemes** [comment]
Updated build is now visible on CurseForge, sorry for the issue...
https://www.curseforge.com/minecraft/mc-mods/ellemes-container-library/files/3865956

**Comment by Gamemassa** [comment]
Thanks again! Your latest revision appears to be working fine now. And no need to apologize. I know how finicky programming can be.
